def armazenar_dicionario_de_dados_como_arquivo_json(dados, nome_arquivo): ...


def ler_arquivo_json_como_dicionario(nome_arquivo): ...


def converter_dicionario_de_dados_para_string_json(dados): ...


def converter_string_json_para_dicionario(dados): ...
